FROM node:22-alpine

ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PNPM_HOME/bin:$PATH"

RUN corepack enable && corepack prepare pnpm@latest --activate
RUN pnpm add -g turbo

WORKDIR /app

COPY pnpm-lock.yaml pnpm-workspace.yaml package.json ./
COPY apps/bff/package.json ./apps/bff/
COPY apps/api-tasks/package.json ./apps/api-tasks/
COPY apps/web/package.json ./apps/web/

RUN pnpm install --no-frozen-lockfile

COPY apps/api-tasks/prisma ./apps/api-tasks/prisma
RUN pnpm --filter api-tasks exec prisma generate

COPY . .

EXPOSE 3000 3001 3002

CMD ["pnpm", "turbo", "dev"]